/**
 * product-data.js
 * Zero Waste Kitchen — Product Catalog
 * Central data source for all product pages, recommendation engine, and analytics tracker.
 * Each product includes affiliate links, attributes for tracking, and recommendation metadata.
 */

const ZWK_PRODUCTS = [
  {
    id: "swedish-dishcloths",
    name: "Swedish Dishcloths",
    slug: "swedish-dishcloths",
    category: "PAPER TOWEL ALTERNATIVE",
    tagline: "Replace 17 rolls of paper towels with one cloth",
    description: "Made from 70% cellulose and 30% cotton, each cloth absorbs up to 15x its weight in water, dries fast, and replaces up to 17 rolls of paper towels.",
    priceRange: "$10 – $23",
    rating: 4.5,
    reviewCount: "9,800+",
    material: "cellulose-cotton blend",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "biodegradable",
    amazonUrl: "https://www.amazon.com/Original-10-Pack-Wettex-Superabsorbent-Dishcloth/dp/B07MX46M6H?tag=zerowasteki07-20",
    image: "images/hero_1.jpg",
    aiImage: "images/ai_dishcloth.jpg",
    tags: ["paper-towel-replacement", "cleaning", "kitchen-essentials"]
  },
  {
    id: "compostable-sponges",
    name: "Compostable Kitchen Sponges",
    slug: "compostable-sponges",
    category: "PLASTIC-FREE CLEANING",
    tagline: "Zero microplastics, 100% compostable",
    description: "Compostable kitchen sponges replace conventional plastic-backed sponges that shed microplastics. Made from natural cellulose and loofah.",
    priceRange: "$8 – $18",
    rating: 4.4,
    reviewCount: "6,200+",
    material: "cellulose-loofah",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "compostable",
    amazonUrl: "https://www.amazon.com/s?k=compostable+kitchen+sponges&tag=zerowasteki07-20",
    image: "images/hero_2.jpg",
    aiImage: "images/ai_dishcloth.jpg",
    tags: ["cleaning", "plastic-free", "kitchen-essentials"]
  },
  {
    id: "reusable-silicone-bags",
    name: "Reusable Silicone Food Storage Bags",
    slug: "reusable-silicone-bags",
    category: "ZERO WASTE STORAGE",
    tagline: "Replace 1,000+ plastic bags per year",
    description: "Reusable silicone food storage bags replace hundreds of single-use plastic bags and pay for themselves within weeks.",
    priceRange: "$8 – $30",
    rating: 4.6,
    reviewCount: "12,400+",
    material: "food-grade silicone",
    aestheticTier: "premium",
    sustainabilityProfile: "reusable-durable",
    amazonUrl: "https://www.amazon.com/s?k=reusable+silicone+food+storage+bags&tag=zerowasteki07-20",
    image: "images/hero_3.jpg",
    aiImage: "images/ai_silicone.jpg",
    tags: ["food-storage", "plastic-free", "kitchen-essentials"]
  },
  {
    id: "bamboo-cutting-board",
    name: "Bamboo Cutting Board",
    slug: "bamboo-cutting-board",
    category: "SUSTAINABLE COOKWARE",
    tagline: "Harder than maple, gentler on knives",
    description: "Bamboo cutting boards are harder than maple, gentler on knife edges, naturally antimicrobial, and made from one of the world's most sustainable materials.",
    priceRange: "$15 – $55",
    rating: 4.7,
    reviewCount: "18,600+",
    material: "moso bamboo",
    aestheticTier: "premium",
    sustainabilityProfile: "renewable-resource",
    amazonUrl: "https://www.amazon.com/s?k=bamboo+cutting+board&tag=zerowasteki07-20",
    image: "images/hero_4.jpg",
    aiImage: "images/ai_bamboo.jpg",
    tags: ["cookware", "sustainable-wood", "kitchen-essentials"]
  },
  {
    id: "stainless-steel-compost-bin",
    name: "Stainless Steel Kitchen Compost Bin",
    slug: "stainless-steel-compost-bin",
    category: "ZERO WASTE COMPOSTING",
    tagline: "Turn food scraps into garden gold",
    description: "The Utopia Kitchen Stainless Steel Compost Bin is the most popular countertop compost bin on Amazon. 1.3-gallon capacity with charcoal filter.",
    priceRange: "$19 – $40",
    rating: 4.5,
    reviewCount: "22,100+",
    material: "stainless steel",
    aestheticTier: "premium",
    sustainabilityProfile: "waste-reduction",
    amazonUrl: "https://www.amazon.com/Utopia-Kitchen-Stainless-Compost-Countertop/dp/B015DRQ36E?tag=zerowasteki07-20",
    image: "images/hero_5.jpg",
    aiImage: "images/ai_compost.jpg",
    tags: ["composting", "kitchen-essentials", "waste-reduction"]
  },
  {
    id: "reusable-produce-bags",
    name: "Reusable Mesh Produce Bags",
    slug: "reusable-produce-bags",
    category: "PLASTIC-FREE GROCERY",
    tagline: "Ditch the plastic produce bags for good",
    description: "Reusable mesh produce bags replace the flimsy plastic bags in the produce section, keep fruits and vegetables fresh longer, and are machine washable.",
    priceRange: "$10 – $25",
    rating: 4.6,
    reviewCount: "8,900+",
    material: "organic cotton mesh",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "reusable-durable",
    amazonUrl: "https://www.amazon.com/s?k=reusable+produce+bags&tag=zerowasteki07-20",
    image: "images/hero_6.jpg",
    aiImage: "images/ai_produce.jpg",
    tags: ["grocery", "plastic-free", "food-storage"]
  },
  {
    id: "glass-food-storage-containers",
    name: "Glass Food Storage Containers with Bamboo Lids",
    slug: "glass-food-storage-containers",
    category: "PLASTIC-FREE STORAGE",
    tagline: "Premium borosilicate glass, zero plastic leaching",
    description: "Glass food storage containers with bamboo lids are the premium choice for plastic-free meal prep. Borosilicate glass is oven, microwave, and freezer safe.",
    priceRange: "$35 – $100",
    rating: 4.7,
    reviewCount: "7,300+",
    material: "borosilicate glass + bamboo",
    aestheticTier: "luxury",
    sustainabilityProfile: "plastic-free",
    amazonUrl: "https://www.amazon.com/s?k=glass+food+storage+containers+with+bamboo+lids&tag=zerowasteki07-20",
    image: "images/hero_7.png",
    aiImage: "images/ai_glass.jpg",
    tags: ["food-storage", "plastic-free", "premium"]
  },
  {
    id: "dish-soap-bar",
    name: "Dish Soap Bar",
    slug: "dish-soap-bar",
    category: "PLASTIC-FREE CLEANING",
    tagline: "One bar = 2-3 plastic bottles eliminated",
    description: "Dish soap bars replace plastic dish soap bottles entirely. One bar lasts as long as 2-3 bottles of liquid dish soap, cuts grease effectively, and is 100% plastic-free.",
    priceRange: "$8 – $20",
    rating: 4.4,
    reviewCount: "4,100+",
    material: "natural soap",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "plastic-free",
    amazonUrl: "https://www.amazon.com/s?k=dish+soap+bar+zero+waste&tag=zerowasteki07-20",
    image: "images/hero_8.png",
    aiImage: "images/ai_dishcloth.jpg",
    tags: ["cleaning", "plastic-free", "kitchen-essentials"]
  },
  {
    id: "bamboo-dish-brush",
    name: "Bamboo Dish Brush",
    slug: "bamboo-dish-brush",
    category: "PLASTIC-FREE CLEANING",
    tagline: "100% natural, fully compostable",
    description: "Bamboo dish brushes replace plastic dish brushes and sponges with a fully natural, compostable alternative. The bamboo handle and natural fiber bristles are biodegradable.",
    priceRange: "$8 – $20",
    rating: 4.5,
    reviewCount: "5,600+",
    material: "bamboo + natural fiber",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "compostable",
    amazonUrl: "https://www.amazon.com/s?k=bamboo+dish+brush&tag=zerowasteki07-20",
    image: "images/ai_bamboo.jpg",
    aiImage: "images/ai_bamboo.jpg",
    tags: ["cleaning", "plastic-free", "bamboo"]
  },
  {
    id: "eco-dishwasher-tablets",
    name: "Eco-Friendly Dishwasher Tablets",
    slug: "eco-dishwasher-tablets",
    category: "PLASTIC-FREE CLEANING",
    tagline: "Powerful clean, zero plastic packaging",
    description: "Eco-friendly dishwasher tablets deliver powerful cleaning performance without phosphates, chlorine bleach, or synthetic fragrances. Plastic-free packaging.",
    priceRange: "$15 – $30",
    rating: 4.3,
    reviewCount: "3,800+",
    material: "plant-based enzymes",
    aestheticTier: "everyday-essential",
    sustainabilityProfile: "plastic-free",
    amazonUrl: "https://www.amazon.com/s?k=eco+friendly+dishwasher+tablets+zero+waste&tag=zerowasteki07-20",
    image: "images/ai_compost.jpg",
    aiImage: "images/ai_compost.jpg",
    tags: ["cleaning", "plastic-free", "dishwasher"]
  }
];

// Export for use in recommendations.js, tracker.js, and dashboard.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ZWK_PRODUCTS;
}
